### PR TITLE
Don't overwrite XAUTHORITY during retry

### PR DESCRIPTION
**Pull request by rsandell**
context.env will throw an IllegalArgumentException when adding an existing
env var, so the XAUTHORITY var needs to be removed when doSetup is called
again during a retry.

### CODE REVIEW

**Comment by rsandell** [comment]
@reviewbybees

**Comment by recena** [comment]
@rsandell Is not there issue for that?

**Comment by rsandell** [comment]
@recena nope, I was debating if I should create one after a bit of searching, but I went with just fixing it instead. ;)

**Comment by recena** [comment]
@rsandell The code looks great. I'd prefer to address this bug through a Jira ticket :bee:

**Comment by jglick** [comment]
:bee:

**Comment by rsandell** [comment]
@reviewbybees done

**Comment by tfennelly** [comment]
:bee:

**Pull request merged**
