### PR TITLE
[JENKINS-36845] ConcurrentModificationException in Pipeline jobs

### PR DESCRIPTION
**Pull request by andresrc**
See [JENKINS-36845](https://issues.jenkins-ci.org/browse/JENKINS-36845)

Besides the fix the PR includes a migration to the new parent POM and Findbugs fixes.

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by armfergom** [comment]
🐝

**Comment by andresrc** [comment]
Thanks @olivergondza . Do you think we could have a release? We are having an increasing number of occurrences.

Thanks again.

**Comment by olivergondza** [comment]
Please, feel free to go ahead.

**Pull request merged**
